#!/usr/bin/env python3

# Created by: Adam Diwani
# Created on: December 13, 2020
# This program tells users if a number is positive or negative


def main():
    
    #Input
    integer_number = float(input("Enter a postive or negative number: "))
    
    #process
    if integer_number > 0:
        print("This number is positive.")
    elif integer_number < 0:
        print("This number is negative.")
    elif integer_number == 0:
        print(0)
    else:
        print("sorry dont know")

if __name__ == "__main__":
    main()
